### ISSUE TITLE
При чём тут ObjectMapper?

### ISSUE THREAD

**Issue by coursar** [MajorPayne36/server-for-client#7]
https://github.com/MajorPayne36/server-for-client/blob/c5ad2ef27f54e8705c0cd3a0b0b78555f264df36/src/main/java/org/example/http/framework/Server.java#L243-L251

**Comment by MajorPayne36** [comment]
Оно используется для преобразования строки в джсон в виде коллекции. В данном случае из строки получаем лист

**Comment by coursar** [comment]
Как связаны JSON и form-urlencoded?

**Comment by MajorPayne36** [comment]
Пересмотрел урок 8-ого числа и понял, что неправильно понял задание. Исправил в предыдущих фиксах
